cards_list_bot_webhook:
    path:     /webhook
    methods:  [POST]
    defaults: { _controller: CardsListBotBundle:Webhook:index }

cards_list_bot_copy:
    path:     /copy/{number}
    methods:  [GET]
    defaults: { _controller: CardsListBotBundle:Copy:index }
