CardsList\BotBundle\Entity\Card:
    type: entity
    table: null
    repositoryClass: CardsList\BotBundle\Repository\CardRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: string
            nullable: false
        user:
            type: bigint
            nullable: false
    lifecycleCallbacks: {  }
